const sidebarLinks = [
  { name: 'Home', link: '/home' },
  { name: 'Subbed Anime', link: '/animes/subbed-anime' },
  { name: 'Dubbed Anime', link: '/animes/dubbed-anime' },
  { name: 'Most Popular', link: '/animes/most-popular' },
  { name: 'Top Airing', link: '/animes/top-airing' },
  { name: 'most favorite', link: '/animes/most-favorite' },
  { name: 'latest completed', link: '/animes/completed' },
  { name: 'recently added', link: '/animes/recently-added' },
  { name: 'recently updated', link: '/animes/recently-updated' },
  { name: 'top upcoming', link: '/animes/top-upcoming' },
  { name: 'A-Z List', link: '/animes/az-list/a' },
  { name: 'Movies', link: '/animes/movie' },
  { name: 'OVAs', link: '/animes/ova' },
  { name: 'ONAs', link: '/animes/ona' },
  { name: 'Specials', link: '/animes/special' },
]

const genres = [
  'action',
  'adventure',
  'cars',
  'comedy',
  'dementia',
  'demons',
  'drama',
  'ecchi',
  'fantasy',
  'game',
  'harem',
  'historical',
  'horror',
  'isekai',
  'josei',
  'kids',
  'magic',
  'martial arts',
  'mecha',
  'military',
  'music',
  'mystery',
  'parody',
  'police',
  'psychological',
  'romance',
  'samurai',
  'school',
  'sci-fi',
  'seinen',
  'shoujo',
  'shoujo ai',
  'shounen',
  'shounen ai',
  'slice of life',
  'space',
  'sports',
  'super power',
  'supernatural',
  'thriller',
  'vampire',
]

export { sidebarLinks, genres }
