const sidebarLinks = [
  { name: 'Home', link: '/home' },
  { name: 'Subbed Anime', link: '/animes/subbed-anime' },
  { name: 'Dubbed Anime', link: '/animes/dubbed-anime' },
  { name: 'Most Popular', link: '/animes/most-popular' },
  { name: 'Top Airing', link: '/animes/top-airing' },
  { name: 'most favorite', link: '/animes/most-favorite' },
  { name: 'latest completed', link: '/animes/completed' },
  { name: 'recently added', link: '/animes/recently-added' },
  { name: 'recently updated', link: '/animes/recently-updated' },
  { name: 'top upcoming', link: '/animes/top-upcoming' },
  { name: 'A-Z List', link: '/animes/az-list' },
  { name: 'Movies', link: '/animes/movie' },
  { name: 'OVAs', link: '/animes/ova' },
  { name: 'ONAs', link: '/animes/ona' },
  { name: 'Specials', link: '/animes/special' },
]

const genres = [
  'action',
  'adventure',
  'cars',
  'comedy',
  'dementia',
  'demons',
  'drama',
  'ecchi',
  'fantasy',
  'game',
  'harem',
  'historical',
  'horror',
  'isekai',
  'josei',
  'kids',
  'magic',
  'martial arts',
  'mecha',
  'military',
  'music',
  'mystery',
  'parody',
  'police',
  'psychological',
  'romance',
  'samurai',
  'school',
  'sci-fi',
  'seinen',
  'shoujo',
  'shoujo ai',
  'shounen',
  'shounen ai',
  'slice of life',
  'space',
  'sports',
  'super power',
  'supernatural',
  'thriller',
  'vampire',
]

const azList = [
  { title: 'ALL', link: '/animes/az-list' },
  { title: '#', link: '/animes/az-list/other' },
  { title: '0-9', link: '/animes/az-list/0-9' },
  { title: 'A', link: '/animes/az-list/A' },
  { title: 'B', link: '/animes/az-list/B' },
  { title: 'C', link: '/animes/az-list/C' },
  { title: 'D', link: '/animes/az-list/D' },
  { title: 'E', link: '/animes/az-list/E' },
  { title: 'F', link: '/animes/az-list/F' },
  { title: 'G', link: '/animes/az-list/G' },
  { title: 'H', link: '/animes/az-list/H' },
  { title: 'I', link: '/animes/az-list/I' },
  { title: 'J', link: '/animes/az-list/J' },
  { title: 'K', link: '/animes/az-list/K' },
  { title: 'L', link: '/animes/az-list/L' },
  { title: 'M', link: '/animes/az-list/M' },
  { title: 'N', link: '/animes/az-list/N' },
  { title: 'O', link: '/animes/az-list/O' },
  { title: 'P', link: '/animes/az-list/P' },
  { title: 'Q', link: '/animes/az-list/Q' },
  { title: 'R', link: '/animes/az-list/R' },
  { title: 'S', link: '/animes/az-list/S' },
  { title: 'T', link: '/animes/az-list/T' },
  { title: 'U', link: '/animes/az-list/U' },
  { title: 'V', link: '/animes/az-list/V' },
  { title: 'W', link: '/animes/az-list/W' },
  { title: 'X', link: '/animes/az-list/X' },
  { title: 'Y', link: '/animes/az-list/Y' },
  { title: 'Z', link: '/animes/az-list/Z' },
]

const validQueries = [
  'top-airing',
  'most-popular',
  'most-favorite',
  'completed',
  'recently-added',
  'recently-updated',
  'top-upcoming',
  'subbed-anime',
  'dubbed-anime',
  'movie',
  'tv',
  'ova',
  'ona',
  'special',
  'az-list',
  'genre',
  'producer',
]

export { sidebarLinks, genres, azList, validQueries }
