const sidebarLinks = [
  { name: 'Home', link: '/home' },
  { name: 'Subbed Anime', link: '/subbed-anime' },
  { name: 'Dubbed Anime', link: '/dubbed-anime' },
  { name: 'Most Popular', link: '/most-popular' },
  { name: 'Top Airing', link: '/top-airing' },
  { name: 'most favorite', link: '/most-favorite' },
  { name: 'latest completed', link: '/completed' },
  { name: 'recently added', link: '/recently-added' },
  { name: 'recently updated', link: '/recently-updated' },
  { name: 'top upcoming', link: '/top-upcoming' },
  { name: 'A-Z List', link: '/az-list' },
  { name: 'Movies', link: '/movie' },
  { name: 'OVAs', link: '/ova' },
  { name: 'ONAs', link: '/ona' },
  { name: 'Specials', link: '/special' },
]

const genres = [
  'action',
  'adventure',
  'cars',
  'comedy',
  'dementia',
  'demons',
  'drama',
  'ecchi',
  'fantasy',
  'game',
  'harem',
  'historical',
  'horror',
  'isekai',
  'josei',
  'kids',
  'magic',
  'martial arts',
  'mecha',
  'military',
  'music',
  'mystery',
  'parody',
  'police',
  'psychological',
  'romance',
  'samurai',
  'school',
  'sci-fi',
  'seinen',
  'shoujo',
  'shoujo ai',
  'shounen',
  'shounen ai',
  'slice of life',
  'space',
  'sports',
  'super power',
  'supernatural',
  'thriller',
  'vampire',
]

const azList = ['all', 'other', '0-9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

const validQueries = [
  'top-airing',
  'most-popular',
  'most-favorite',
  'completed',
  'recently-added',
  'recently-updated',
  'top-upcoming',
  'subbed-anime',
  'dubbed-anime',
  'movie',
  'tv',
  'ova',
  'ona',
  'special',
  'az-list',
  'genre',
  'producer',
]

export { sidebarLinks, genres, azList, validQueries }
